---
title: "金利"
---

時点 $t$ を満期として $1$ を支払う**割引債**（**ゼロクーポン債**）の時点 $s$ における価格を $Z_s(t)$ とする。時点 $s$ において約定される時点 $s$ から $t$ までの連続複利ベースの**スポットレート**を $R_s(t)$ とすると、以下の関係が成り立つ。

$$
Z_s(t)=e^{-(t-s)R_s(t)}
$$

$$
R_s(t)=-\frac{1}{t-s}\log Z_s(t)
$$

スポットレート $R_s(t)$ において、期間 $t-s$ を極限までゼロに近づけるときの瞬間的な金利を**瞬間スポットレート**、または**ショートレート**と呼び $r_s$ で表す。

$$
r_s=\lim_{t\to s}R_s(t)
$$

満期までの期間 $t-s$ を変数として置きなおした関数 $C_s(x)=R_s(s+x)$ を（連続複利ベースの）スポットレートカーブと呼ぶ。

時点 $s$ において約定される時点 $t$ から時点 $u$ までの連続複利ベースの**フォワードレート**を $F_s(t,u)$ とおく。無裁定条件の下では、時点 $s$ から $u$ までスポットレートで運用することによるリターンと、時点 $s$ から $t$ までスポットレートで運用し、時点 $t$ から $u$ までフォワードレートで再投資することで得られるリターンは一致しなければならないため、以下の関係が成立する。

$$
e^{(t-s)R_s(t)}e^{(u-t)F_s(t,u)} = e^{(u-s)R_s(u)}
$$

これを $F_s(t,u)$ に関して整理すれば以下の通りとなる。

$$
F_s(t,u)=\frac{(u-s)R_s(u)-(t-s)R_s(t)}{u-t}
=-\frac{\log{Z_s(u)}-\log{Z_s(t)}}{u-t}
$$

フォワードレート $F_s(t,u)$ において、契約期間 $u-t$ を極限までゼロに近づけるときの瞬間的な金利を**瞬間フォワードレート**と呼び、 $f_s(t)$ で表す。

$$
f_s(t)=\lim_{u\to t} F_s(t,u)
=-\frac{\partial}{\partial t}\log{Z_s(t)}
$$

スポットレート $R_s(t)$ は瞬間フォワードレート $f_s(u)$ の期間平均であり、以下の積分で表現できる。

$$
R_s(t)=\frac{1}{t-s}\int_s^t f_s(u)du
$$

割引債価格を瞬間フォワードレートで表せば、以下の通りとなる。

$$
Z_s(t)=\exp\left(-\int_s^t f_s(u) du\right)
$$

スポットレートとフォワードレートの関係は、評価時点と期間を軸とする2次元平面を用いて以下のように表すこともできる。

```{r}
#| echo: false
#| warning: false
library(ggplot2)

# 描画用の基準点（例：評価時点 s=1、開始時点 t=3、終了時点 u=5）
s <- 1
t <- 3
u <- 5

# グラフの構築
p <- ggplot() +
  # baseline
  geom_abline(
    slope = 1, intercept = 0, linewidth = 0.5, linetype = 3
  ) +
  # spot rate
  geom_segment(aes(x = s, y = s, xend = s, yend = t),
               arrow = arrow(length = unit(0.3, "cm")),
               linewidth = 0.7) +
  # forward rate
  geom_segment(aes(x = s, y = t, xend = s, yend = u),
               arrow = arrow(length = unit(0.3, "cm")),
               linewidth = 0.7) +
  # instantaneous forward
  geom_point(aes(x = s, y = t), size = 2, shape = 16) +
  # short rate
  geom_point(aes(x = s, y = s), size = 2, shape = 16) +
  geom_text(aes(x = s + 0.2, y = (s + t) / 2, label = "Spot Rate : R_1(3)"),
            hjust = 0, size = 4) +
  geom_text(aes(x = s + 0.2, y = (t + u) / 2, label = "Forward Rate : F_1(3, 5)"),
            hjust = 0, size = 4) +
  geom_text(aes(x = s + 0.2, y = t, label = "Instantaneous Forward : f_1(3)"),
            hjust = 0, size = 4) +
  geom_text(aes(x = s + 0.2, y = s, label = "Instantaneous Spot (Short Rate) : r_1"),
            hjust = 0, size = 4) +
  coord_fixed(xlim = c(0, 6), ylim = c(0, 6)) +
  labs(
    x = "Observation Time",
    y = "Term"
  ) +
  theme_bw(base_family="serif", base_size=14)

print(p)
```

### 確率的期間構造モデル

金融派生商品の理論価格評価などに用いられる金利の期間構造モデルは確率的なものであり、割引債債価格 $Z_s(t)$ を導出するアプローチの違いによって、**フォワードレートモデル**と**ショートレートモデル**の2つに大別される。

フォワードレートモデルでは、将来の各時点における瞬間フォワードレート $f_s(t)$ の経時的な変動がすべてモデル化の対象とされ、割引債価格 $Z_s(t)$ は評価時点 $s$ で観察される瞬間フォワードレートを対象期間にわたって積分することで直接的に定まる。

$$
Z_s(t) = \exp\left(-\int_s^t f_s(u) du\right)
$$

ショートレートモデルでは、瞬間スポットレート $r_s$ の変動だけがモデル化の対象とされ、割引債価格 $Z_s(t)$ は、リスク中立測度 $\mathbb{Q}$ の下でショートレート経路を積分して得られる割引因子の期待値を評価することで導かれる。

$$
Z_s(t) = \mathbb{E}^{\mathbb{Q}}_s \left[ \exp\left(-\int_s^t r_u du\right) \right]
$$

### 決定論的アプローチ

将来収支予測やストレステストなどの目的では、金利の期間構造が一定のシナリオに基づいて決定論的に推移すると仮定するアプローチも採用される。**フォワードレート不変シナリオ**では、特定の時点 $t$ における瞬間フォワードレートが評価時点 $s$ に依存しない（$f_s(t) = f(t)$）。**イールドカーブ不変シナリオ**では、イールドカーブの形状が評価時点 $s$ に依存しない（$f_s(t) = h(t-s)$）。**パラレルシフトシナリオ**では、イールドカーブ全体が平行移動する。**ツイストシナリオ**では、短期金利と長期金利の変動幅が異なることによって、イールドカーブの傾きが変動する。
